# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

 variables:
   solitionDir: 'JrWebApp'

steps:
  - script: pwd
    displayName: 'what directory are we in?'

  - script: ls -la
    displayName: 'what files are in this folder?'

  - script: dotnet build
    displayName: 'dotnet build'
    workingDirectory: $(solitionDir)

# steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
