# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

 #variables:
 #  solutionDir: 'JrWebApp'

steps:
  - script: pwd
    displayName: 'what directory are we in?'

  - script: ls -la
    displayName: 'what files are in this folder?'

  - script: dotnet build
    displayName: 'dotnet build'
    workingDirectory: 'JrWebApp'

  - task: DotNetCoreCLI@2
    displayName: run unit test
    inputs:
      command: test
      workingDirectory: 'JrWebApp/test/JrWebAppSolution.UnitTests'

  - script: dotnet publish -o $(build.artifactStagingDirectory)
    displayName: 'dotnet publish'
    workingDirectory: 'JrWebApp'

  - task: PublishPipelineArtifact@1
    inputs:
      #targetPath: '$(Pipeline.Workspace)'
      targetPath: '$(build.artifactStagingDirectory)'
      artifact: 'drop'
      publishLocation: 'pipeline'

# steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
