# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

 #variables:
 #  solutionDir: 'JrWebApp'

stages:
- stage: build
  jobs:
    - job: build
      steps:
      - script: pwd
        displayName: 'what directory are we in?'

      - script: ls -la
        displayName: 'what files are in this folder?'

      # - task: DotNetCoreCLI@2
      #   displayName: 'DotNet Restore'
      #   inputs:
      #     command: 'restore'
      #     projects: 'JrWebApp/UnitTests.csproj'
      #     feedsToUse: 'config'

      - script: dotnet build
        displayName: 'dotnet build'
        workingDirectory: 'JrWebApp'

      - task: DotNetCoreCLI@2
        displayName: run unit test
        inputs:
          command: test
          workingDirectory: 'UnitTests'

      - script: dotnet publish -o $(build.artifactStagingDirectory)
        displayName: 'dotnet publish'
        workingDirectory: 'JrWebApp'

      - task: PublishPipelineArtifact@1
        inputs:
          #targetPath: '$(Pipeline.Workspace)'
          targetPath: '$(build.artifactStagingDirectory)'
          artifact: 'drop'
          publishLocation: 'pipeline'

      # - task: AzureRmWebAppDeployment@4
      #   inputs:
      #     ConnectionType: 'AzureRM'
      #     azureSubscription: 'Visual Studio Professional(5153a677-5431-4077-b3c1-4dd21eb14f97)'
      #     appType: 'webAppLinux'
      #     WebAppName: 'JRWebLab'
      #     packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
          
- stage: deploy_to_test
  jobs:
    - job: deployToAppService
      displayName: 'deploy to azure app service -- test deployment slot'
      steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'drop'
            targetPath: '$(Pipeline.Workspace)/drop'
        - script: pwd
          displayName: what dir is this?
          workingDirectory: '$(Pipeline.Workspace)'
        - script: ls - la
          displayName: what's on disk?
          workingDirectory: '$(Pipeline.Workspace)'
